const SET_DATA = 'SET_DATA';
const ADD_SYMBOL = 'ADD_SYMBOL';
const EDIT_SYMBOL = 'EDIT_SYMBOL'
const OPEN_MODAL_CONFIRM_REMOVE = 'OPEN_MODAL_CONFIRM_REMOVE';
const CLOSE_MODAL_CONFIRM_REMOVE = 'CLOSE_MODAL_CONFIRM_REMOVE';
const REMOVE_SYMBOL = 'REMOVE_SYMBOL';
const OPEN_MODAL_EDIT_SYMBOL = 'OPEN_MODAL_EDIT_SYMBOL'
const CLOSE_MODAL_EDIT_SYMBOL = 'CLOSE_MODAL_EDIT_SYMBOL'
const OPEN_MODAL_ADD_CATEGORY = 'OPEN_MODAL_ADD_CATEGORY'
const CLOSE_MODAL_ADD_CATEGORY = 'CLOSE_MODAL_ADD_CATEGORY'

export {
    SET_DATA,
    ADD_SYMBOL,
    CLOSE_MODAL_CONFIRM_REMOVE,
    OPEN_MODAL_CONFIRM_REMOVE,
    REMOVE_SYMBOL,
    OPEN_MODAL_EDIT_SYMBOL,
    CLOSE_MODAL_EDIT_SYMBOL,
    EDIT_SYMBOL,
    OPEN_MODAL_ADD_CATEGORY,
    CLOSE_MODAL_ADD_CATEGORY
};


// API

export const API = 'http://localhost:1235/kruk';

export const API_GET_ALL = '/all';

export const API_SEND_NEW_SYMBOL = '/add';

export const API_EDIT_SYMBOL = '/edit';

