const SET_SYMBOLS = 'SET_SYMBOLS'
const ADD_SYMBOL = 'ADD_SYMBOL'
const EDIT_SYMBOL = 'EDIT_SYMBOL'
const OPEN_MODAL_CONFIRM_REMOVE = 'OPEN_MODAL_CONFIRM_REMOVE'
const CLOSE_MODAL_CONFIRM_REMOVE = 'CLOSE_MODAL_CONFIRM_REMOVE'
const REMOVE_SYMBOL = 'REMOVE_SYMBOL'
const OPEN_MODAL_EDIT_SYMBOL = 'OPEN_MODAL_EDIT_SYMBOL'
const CLOSE_MODAL_EDIT_SYMBOL = 'CLOSE_MODAL_EDIT_SYMBOL'
const OPEN_MODAL_ADD_CATEGORY = 'OPEN_MODAL_ADD_CATEGORY'
const CLOSE_MODAL_ADD_CATEGORY = 'CLOSE_MODAL_ADD_CATEGORY'

const SET_COMPOSITIONS = 'SET_COMPOSITIONS'
const ADD_COMPOSITIONS = 'ADD_COMPOSITIONS'
const REMOVE_COMPOSITIONS = 'REMOVE_COMPOSITIONS'

export {
  SET_SYMBOLS,
  ADD_SYMBOL,
  CLOSE_MODAL_CONFIRM_REMOVE,
  OPEN_MODAL_CONFIRM_REMOVE,
  REMOVE_SYMBOL,
  OPEN_MODAL_EDIT_SYMBOL,
  CLOSE_MODAL_EDIT_SYMBOL,
  EDIT_SYMBOL,
  OPEN_MODAL_ADD_CATEGORY,
  CLOSE_MODAL_ADD_CATEGORY,
  SET_COMPOSITIONS,
  ADD_COMPOSITIONS,
  REMOVE_COMPOSITIONS,
}

// API

export const API = 'http://localhost:1235'

export const API_GET_ALL_SYMBOLS = '/kruk/all'

export const API_GET_ALL_COMPOSITIONS = '/composition/all'

export const API_SEND_NEW_SYMBOL = '/kruk/add'

export const API_SEND_NEW_COMPOSITION = '/composition/add'

export const API_EDIT_SYMBOL = '/kruk/edit'
